In [1]:
import pandas as pd 
gea = pd.read_excel("Gea_Reviews_2022_2026_Combined.xlsx")
pelagos = pd.read_excel("Pelagos_Reviews_2022_2026_Combined.xlsx")

print("Gea loaded:", len(gea), "reviews")
print("Pelagos loaded:", len(pelagos), "reviews")

Gea loaded: 329 reviews
Pelagos loaded: 1347 reviews

In [2]:
print("GEA DATASET")
print("Shape:", gea.shape)
print("Columns:")
print(gea.columns.tolist())

print("----------------------------------------------")

print ("PELAGOS DATASET")
print("Shape:", pelagos.shape)
print("Columns:")
print(pelagos.columns.tolist())

GEA DATASET
Shape: (329, 27)
Columns:
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Search criteria: Reviews on  from January 1, 2022 to December 1, 2022', 'Search criteria: Reviews on  from January 1, 2023 to December 1, 2023', 'Search criteria: Reviews on  from January 1, 2024 to December 1, 2024', 'Search criteria: Reviews on  from January 1, 2025 to August 1, 2026']
----------------------------------------------
PELAGOS DATASET
Shape: (1347, 4)
Columns:
['Search criteria: Reviews on  from January 1, 2022 to December 1, 2022', 'Search criteria: Reviews on  from January 1, 2023 to December 1, 2023', 'Search criteria: Reviews on  from January 1, 2024 to December 1, 2024', 'Search criteria: Reviews on  from January 1, 2025 to August 1, 2026']

In [3]:
print("GEA COLUMNS")
print(gea.columns.tolist())

print("PELAGOS COLUMNS")
print(pelagos.columns.tolist())

GEA COLUMNS
['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Search criteria: Reviews on  from January 1, 2022 to December 1, 2022', 'Search criteria: Reviews on  from January 1, 2023 to December 1, 2023', 'Search criteria: Reviews on  from January 1, 2024 to December 1, 2024', 'Search criteria: Reviews on  from January 1, 2025 to August 1, 2026']
PELAGOS COLUMNS
['Search criteria: Reviews on  from January 1, 2022 to December 1, 2022', 'Search criteria: Reviews on  from January 1, 2023 to December 1, 2023', 'Search criteria: Reviews on  from January 1, 2024 to December 1, 2024', 'Search criteria: Reviews on  from January 1, 2025 to August 1, 2026']

In [4]:
import pandas as pd
test = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2022.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=7
)
print("Shape:", test.shape)
print("\nColumns:")
print(test.columns.tolist())

test.head()

Shape: (196, 1)

Columns:
['Search criteria: Reviews on  from January 1, 2022 to December 1, 2022']

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Search criteria: Reviews on  from January 1, 2022 to December 1, 2022
Hotel                             Review Site Revinate Collected Date Review Date Rating Review Title                          Review                                             Subrating: Cleanliness Subrating: Location Subrating: Rooms Subrating: Service Subrating: Value Subrating: Sleep Quality Recommended Response                                           Review Link                                        Ticket External ID Language              Author           Author Location Review ID Response Submitted Date                               Response Posted Date
Katikies Santorini- Pelagos House TripAdvisor 11/26/22                11/25/22    5      The best way to experience Santorini… This hotel is absolutely amazing. The suites an... NaN                    NaN                 NaN              NaN                NaN              NaN                      NaN         Dear Destination32805,    Thank you for taking ... http://www.tripadvisor.com/Hotel_Review-g482941... NaN    LW0815      English               Destination32805 NaN             893021706 11/28/22                                                          11/28/22
                                  Google      11/26/22                11/25/22    5      NaN                                   Worth every penny. The staff were amazing. The ... NaN                    NaN                 NaN              NaN                NaN              NaN                      NaN         Dear LA,    Thank your very much for your 5 sta... https://www.google.com/search?q=Katikies+The+Ho... NaN    LW0815      English               L A              NaN             893008112 11/28/22                                                          11/28/22
                                  Ctrip       11/26/22                11/24/22    5      NaN                                   非常滿意，環境非常好👍                                        NaN                    NaN                 NaN              NaN                NaN              NaN                      NaN         Dear valued guest,Thank you for your positive f... http://hotels.ctrip.com/hotel/2133943.html         NaN    LW0815      Chinese (Traditional) CHUNTAO          NaN             893004821 NaN                                                               11/07/24
                                  Travelocity 11/20/22                11/12/22    5      NaN                                   Excelente atención desde antes de llegar, ademá... 5                      NaN                 NaN              5                  NaN              NaN                      NaN         Dear Juan Miguel,Thank you very much for taking... http://www.travelocity.com/h4056090.Hotel-Infor... NaN    LW0815      Spanish               Juan Miguel      NaN             891039353 11/21/22                                                          11/22/22

In [5]:
test = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2022.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
print("Shape:", test.shape)
print("Number of columns:", len(test.columns))
print(test.columns.tolist())

test.head()

Shape: (195, 24)
Number of columns: 24
['Hotel', 'Review Site', 'Revinate Collected Date', 'Review Date', 'Rating', 'Review Title', 'Review', 'Subrating: Cleanliness', 'Subrating: Location', 'Subrating: Rooms', 'Subrating: Service', 'Subrating: Value', 'Subrating: Sleep Quality', 'Recommended', 'Response', 'Review Link', 'Ticket', 'External ID', 'Language', 'Author', 'Author Location', 'Review ID', 'Response Submitted Date', 'Response Posted Date']

,Hotel,Review Site,Revinate Collected Date,Review Date,Rating,Review Title,Review,Subrating: Cleanliness,Subrating: Location,Subrating: Rooms,...,Response,Review Link,Ticket,External ID,Language,Author,Author Location,Review ID,Response Submitted Date,Response Posted Date
0,Katikies Santorini- Pelagos House,TripAdvisor,11/26/22,11/25/22,5.0,The best way to experience Santorini…,This hotel is absolutely amazing. The suites a...,NaN,NaN,NaN,...,"Dear Destination32805, Thank you for taking...",http://www.tripadvisor.com/Hotel_Review-g48294...,NaN,LW0815,English,Destination32805,NaN,893021706,11/28/22,11/28/22
1,Katikies Santorini- Pelagos House,Google,11/26/22,11/25/22,5.0,NaN,Worth every penny. The staff were amazing. The...,NaN,NaN,NaN,...,"Dear LA, Thank your very much for your 5 st...",https://www.google.com/search?q=Katikies+The+H...,NaN,LW0815,English,L A,NaN,893008112,11/28/22,11/28/22
2,Katikies Santorini- Pelagos House,Ctrip,11/26/22,11/24/22,5.0,NaN,非常滿意，環境非常好👍,NaN,NaN,NaN,...,"Dear valued guest,Thank you for your positive ...",http://hotels.ctrip.com/hotel/2133943.html,NaN,LW0815,Chinese (Traditional),CHUNTAO,NaN,893004821,NaN,11/07/24
3,Katikies Santorini- Pelagos House,Travelocity,11/20/22,11/12/22,5.0,NaN,"Excelente atención desde antes de llegar, adem...",5.0,NaN,NaN,...,"Dear Juan Miguel,Thank you very much for takin...",http://www.travelocity.com/h4056090.Hotel-Info...,NaN,LW0815,Spanish,Juan Miguel,NaN,891039353,11/21/22,11/22/22
4,Katikies Santorini- Pelagos House,Booking.com,11/18/22,11/18/22,5.0,NaN,Good: 很美的日落景,5.0,5.0,5.0,...,"Dear Chunkwan, Thank you very much for taki...",http://www.booking.com/hotel/gr/katikies.en.ht...,NaN,LW0815,Chinese (Simplified),CHUNKWAN,China,890859811,11/21/22,11/22/22

In [6]:
pelagos_2022 = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2022.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
pelagos_2023 = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2023.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
pelagos_2024 = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2024.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
pelagos_2025_26 = pd.read_csv(
    "Revinate_reviews_export_Pelagos_2025_26.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
print("2022:", pelagos_2022.shape)
print("2023:", pelagos_2023.shape)
print("2024:", pelagos_2024.shape)
print("2025_26:", pelagos_2025_26.shape)

2022: (195, 24)
2023: (278, 24)
2024: (536, 24)
2025_26: (335, 24)

In [7]:
pelagos = pd.concat(
    [pelagos_2022, pelagos_2023, pelagos_2024, pelagos_2025_26],
    ignore_index=True
)
print("Pelagos combined successfully!")
print("Total reviews:", len(pelagos))
print("Shape:", pelagos.shape)

pelagos.head()

Pelagos combined successfully!
Total reviews: 1344
Shape: (1344, 24)

,Hotel,Review Site,Revinate Collected Date,Review Date,Rating,Review Title,Review,Subrating: Cleanliness,Subrating: Location,Subrating: Rooms,...,Response,Review Link,Ticket,External ID,Language,Author,Author Location,Review ID,Response Submitted Date,Response Posted Date
0,Katikies Santorini- Pelagos House,TripAdvisor,11/26/22,11/25/22,5.0,The best way to experience Santorini…,This hotel is absolutely amazing. The suites a...,NaN,NaN,NaN,...,"Dear Destination32805, Thank you for taking...",http://www.tripadvisor.com/Hotel_Review-g48294...,NaN,LW0815,English,Destination32805,NaN,893021706,11/28/22,11/28/22
1,Katikies Santorini- Pelagos House,Google,11/26/22,11/25/22,5.0,NaN,Worth every penny. The staff were amazing. The...,NaN,NaN,NaN,...,"Dear LA, Thank your very much for your 5 st...",https://www.google.com/search?q=Katikies+The+H...,NaN,LW0815,English,L A,NaN,893008112,11/28/22,11/28/22
2,Katikies Santorini- Pelagos House,Ctrip,11/26/22,11/24/22,5.0,NaN,非常滿意，環境非常好👍,NaN,NaN,NaN,...,"Dear valued guest,Thank you for your positive ...",http://hotels.ctrip.com/hotel/2133943.html,NaN,LW0815,Chinese (Traditional),CHUNTAO,NaN,893004821,NaN,11/07/24
3,Katikies Santorini- Pelagos House,Travelocity,11/20/22,11/12/22,5.0,NaN,"Excelente atención desde antes de llegar, adem...",5.0,NaN,NaN,...,"Dear Juan Miguel,Thank you very much for takin...",http://www.travelocity.com/h4056090.Hotel-Info...,NaN,LW0815,Spanish,Juan Miguel,NaN,891039353,11/21/22,11/22/22
4,Katikies Santorini- Pelagos House,Booking.com,11/18/22,11/18/22,5.0,NaN,Good: 很美的日落景,5.0,5.0,5.0,...,"Dear Chunkwan, Thank you very much for taki...",http://www.booking.com/hotel/gr/katikies.en.ht...,NaN,LW0815,Chinese (Simplified),CHUNKWAN,China,890859811,11/21/22,11/22/22

In [8]:
gea_2022 = pd.read_csv(
    "Revinate_reviews_export_Gea_2022.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
gea_2023 = pd.read_csv(
    "Revinate_reviews_export_Gea_2023.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
gea_2024 = pd.read_csv(
    "Revinate_reviews_export_Gea_2024.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
gea_2025_26 = pd.read_csv(
    "Revinate_reviews_export_Gea_2025_26.csv",
    encoding="utf-16",
    sep="\t",
    skiprows=8
)
print("2022:",gea_2022.shape)
print("2023:", gea_2023.shape)
print("2024:", gea_2024.shape)
print("2025_26:", gea_2025_26.shape)

2022: (61, 24)
2023: (77, 24)
2024: (97, 24)
2025_26: (90, 24)

In [9]:
gea = pd.concat(
    [gea_2022, gea_2023, gea_2024, gea_2025_26],
    ignore_index=True
)

print("Gea combined successfully!")
print("Total reviews:", len(gea))
print("Shape:", gea.shape)

gea.head()

Gea combined successfully!
Total reviews: 325
Shape: (325, 24)

,Hotel,Review Site,Revinate Collected Date,Review Date,Rating,Review Title,Review,Subrating: Cleanliness,Subrating: Location,Subrating: Rooms,...,Response,Review Link,Ticket,External ID,Language,Author,Author Location,Review ID,Response Submitted Date,Response Posted Date
0,Katikies Santorini- Gea House,Priceline,12/01/22,12/01/22,4.0,Excellent.,Good: staff location Bad: we didn’t receiv...,NaN,NaN,NaN,...,NaN,https://www.priceline.com/hotel-deals/h3261004...,NaN,LW0820,English,Shana,VG,1134445675,NaN,NaN
1,Katikies Santorini- Gea House,Expedia,11/13/22,11/12/22,5.0,NaN,Of course the views are to die for! Room was v...,5.0,NaN,NaN,...,"Dear Denise,Thank you for taking the time to s...",http://www.expedia.com/h1356495.Hotel-Informat...,NaN,LW0820,English,Denise,NaN,889302296,11/14/22,11/14/22
2,Katikies Santorini- Gea House,Ctrip,11/13/22,11/13/22,5.0,Outstanding,Of course the views are to die for! Room was v...,NaN,NaN,NaN,...,"Dear Denise,Thank you for taking the time to s...",http://hotels.ctrip.com/hotel/759299.html,NaN,LW0820,English,Denise,NaN,973575188,NaN,07/26/24
3,Katikies Santorini- Gea House,Booking.com,11/01/22,11/01/22,5.0,exceptionnel,Good: vue incroyable piscine petit déjeuner,5.0,5.0,5.0,...,"Chère Laetitia, Merci beaucoup d'avoir pris...",http://www.booking.com/hotel/gr/kirini-suites-...,NaN,LW0820,French,Laetitia,France,885648720,11/01/22,11/02/22
4,Katikies Santorini- Gea House,Booking.com,10/28/22,10/28/22,5.0,NaN,NaN,5.0,5.0,5.0,...,NaN,http://www.booking.com/hotel/gr/kirini-suites-...,NaN,LW0820,NaN,Lisa,United States of America,884883477,NaN,NaN

In [10]:
#Data quality and missing values identified 
print("Gea - Missing values:")
print(gea.isnull().sum())

print("\n" + "="*50)

print("Pelagos - Missing values:")
print(pelagos.isnull().sum())

print("\n" + "="*50)

print("Gea duplicate rows:", gea.duplicated().sum())
print("Pelagos duplicate rows:", pelagos.duplicated().sum())

Gea - Missing values:
Hotel                         0
Review Site                   0
Revinate Collected Date       0
Review Date                   0
Rating                        0
Review Title                117
Review                       66
Subrating: Cleanliness      164
Subrating: Location         216
Subrating: Rooms            210
Subrating: Service          232
Subrating: Value            217
Subrating: Sleep Quality    306
Recommended                 263
Response                    188
Review Link                   0
Ticket                      325
External ID                   0
Language                     34
Author                        0
Author Location             177
Review ID                     0
Response Submitted Date     235
Response Posted Date        188
dtype: int64

==================================================
Pelagos - Missing values:
Hotel                          0
Review Site                    0
Revinate Collected Date        0
Review Date                    0
Rating                         2
Review Title                 852
Review                       421
Subrating: Cleanliness       994
Subrating: Location          693
Subrating: Rooms             687
Subrating: Service           760
Subrating: Value            1091
Subrating: Sleep Quality    1289
Recommended                 1119
Response                     606
Review Link                    0
Ticket                      1344
External ID                    0
Language                     369
Author                         0
Author Location              951
Review ID                      0
Response Submitted Date      707
Response Posted Date         606
dtype: int64

==================================================
Gea duplicate rows: 0
Pelagos duplicate rows: 0

In [11]:
#Can review titles rescue reviews with missing text?
print("Gea")
print("Missing Review:", gea["Review"].isna().sum())
print("Missing Review Title:", gea["Review Title"].isna().sum())
print("Missing BOTH:",
      (gea["Review"].isna() & gea["Review Title"].isna()).sum() 
      )
print("\nPelagos")
print("Missing Review:", pelagos["Review"].isna().sum())
print("Missing Review Title:", pelagos["Review Title"].isna().sum())
print("Missing BOTH:", 
      (pelagos["Review"].isna() & pelagos["Review Title"].isna()).sum()
      )

Gea
Missing Review: 66
Missing Review Title: 117
Missing BOTH: 56

Pelagos
Missing Review: 421
Missing Review Title: 852
Missing BOTH: 381

In [12]:
# Create combined text field for NLP analysis

gea["Review_Text"] = (
gea["Review Title"].fillna("").astype(str).str.strip()
+ " "
+ gea["Review"].fillna("").astype(str).str.strip()
).str.strip()

pelagos["Review_Text"] = (
pelagos["Review Title"].fillna("").astype(str).str.strip()
+ " "
+ pelagos["Review"].fillna("").astype(str).str.strip()
).str.strip()

# Count reviews containing usable text
print("Gea reviews with text:", (gea["Review_Text"] != "").sum())
print("Pelagos reviews with text:", (pelagos["Review_Text"] != "").sum())

# Preview
gea[["Review Title", "Review", "Review_Text"]].head()

Gea reviews with text: 269
Pelagos reviews with text: 963

,Review Title,Review,Review_Text
0,Excellent.,Good: staff location Bad: we didn’t receiv...,Excellent. Good: staff location Bad: we di...
1,NaN,Of course the views are to die for! Room was v...,Of course the views are to die for! Room was v...
2,Outstanding,Of course the views are to die for! Room was v...,Outstanding Of course the views are to die for...
3,exceptionnel,Good: vue incroyable piscine petit déjeuner,exceptionnel Good: vue incroyable piscine ...
4,NaN,NaN,

In [13]:
#Creation of NLP dataset containing only reviews with usable text
gea_nlp = gea[gea["Review_Text"].str.strip() != ""].copy()
pelagos_nlp = pelagos[pelagos["Review_Text"].str.strip() != ""].copy()

#To reset the index
gea_nlp.reset_index(drop=True, inplace=True)
pelagos_nlp.reset_index(drop=True, inplace=True)

print("Original Gea:", len(gea))
print("Gea NLP dataset:", len(gea_nlp))

print("Original Pelagos:", len(pelagos))
print("Pelagos NLP datast:", len(pelagos_nlp))

print("Total reviews available for NLP:",
      len(gea_nlp) + len(pelagos_nlp))

Original Gea: 325
Gea NLP dataset: 269
Original Pelagos: 1344
Pelagos NLP datast: 963
Total reviews available for NLP: 1232

In [14]:
#Checking language distribution in NLP datasets

print("Gea - Languages")
print(gea_nlp["Language"].value_counts(dropna=False))

print("\n" + "=" * 50)

print("Pelagos - Languages")
print(pelagos_nlp["Language"].value_counts(dropna=False))

Gea - Languages
Language
English                  222
Portuguese                15
German                     7
French                     6
Japanese                   6
Spanish                    5
Chinese (Traditional)      3
Korean                     1
Italian                    1
Romanian                   1
Hebrew                     1
Swedish                    1
Name: count, dtype: int64

==================================================
Pelagos - Languages
Language
English                  752
NaN                       68
Japanese                  26
Portuguese                23
Chinese (Traditional)     18
Spanish                   16
French                    16
German                    12
Italian                    7
Korean                     4
Chinese (Simplified)       4
Russian                    4
Polish                     3
Arabic                     3
Danish                     2
Turkish                    2
Hebrew                     2
Dutch                      1
Name: count, dtype: int64

In [15]:
#Inspection of reviews where Revinate has no language label 
pelagos_unknown_language = pelagos_nlp[
    pelagos_nlp["Language"].isna()
    ][["Review Site", "Review Title", "Review", "Review_Text"]]
print("Reviews with missing language:", len(pelagos_unknown_language))

pelagos_unknown_language.head(20)

Reviews with missing language: 68

,Review Site,Review Title,Review,Review_Text
185,Google,NaN,Optimal,Optimal
280,Google,NaN,"Ένα μαγικό σκηνικό Καλντέρας, σε ένα άψογο και...","Ένα μαγικό σκηνικό Καλντέρας, σε ένα άψογο και..."
400,Google,NaN,Σε αυτό το χώρο θα γράψω τα αξιοσημείωτα από τ...,Σε αυτό το χώρο θα γράψω τα αξιοσημείωτα από τ...
421,Google,NaN,Ένα από τα καλυτερα καταλύματα που έχω επισκεφ...,Ένα από τα καλυτερα καταλύματα που έχω επισκεφ...
423,Google,NaN,Ένα επίγειος παράδεισος Hotel highlights: ...,Ένα επίγειος παράδεισος Hotel highlights: ...
425,Google,NaN,Εξαιρετικό ξενοδοχείο με εξαιρετική εξυπηρέτησ...,Εξαιρετικό ξενοδοχείο με εξαιρετική εξυπηρέτησ...
426,Google,NaN,Πάρα πολύ ωραίο ξενοδοχείο στην Οία Σαντορίνης...,Πάρα πολύ ωραίο ξενοδοχείο στην Οία Σαντορίνης...
428,Google,NaN,Οι Εξυπηρέτηση ήταν πάρα πολύ καλή και τα δωμά...,Οι Εξυπηρέτηση ήταν πάρα πολύ καλή και τα δωμά...
436,Google,NaN,Πολύ καθαρός χώρος και ευγενικό προσωπικό.Η τι...,Πολύ καθαρός χώρος και ευγενικό προσωπικό.Η τι...
437,Google,NaN,"Φοβερό ξενοδοχείο, μου άρεσαν όλα πάρα πολύ, ω...","Φοβερό ξενοδοχείο, μου άρεσαν όλα πάρα πολύ, ω..."
439,Google,NaN,Πραγματικά τέλειο ξενοδοχείο αξίζει τα λεφτά τ...,Πραγματικά τέλειο ξενοδοχείο αξίζει τα λεφτά τ...
441,Google,NaN,Καταπληκτική θέα Hotel highlights: Great view,Καταπληκτική θέα Hotel highlights: Great view
442,Google,NaN,Πέρασα υπέροχα θα ξανά πήγαινα,Πέρασα υπέροχα θα ξανά πήγαινα
444,Google,NaN,Άριστη τοποθεσία καθώς και εξυπηρέτηση,Άριστη τοποθεσία καθώς και εξυπηρέτηση
445,Google,NaN,Η διαμονή μου στο ξενοδοχείο ήταν εξαιρετική. ...,Η διαμονή μου στο ξενοδοχείο ήταν εξαιρετική. ...
446,Google,NaN,Όλα αψογαRooms: Υπέροχα και ανεταNearby activi...,Όλα αψογαRooms: Υπέροχα και ανεταNearby activi...
447,Google,NaN,Φτάσαμε στις Katikies Santorini η εξυπηρέτηση ...,Φτάσαμε στις Katikies Santorini η εξυπηρέτηση ...
450,Google,NaN,Πολύ ωραία επιλογή με άμεση εξυπηρέτηση και φι...,Πολύ ωραία επιλογή με άμεση εξυπηρέτηση και φι...
451,Google,NaN,Τα πάντα φανταστικα Hotel highlights: Luxu...,Τα πάντα φανταστικα Hotel highlights: Luxu...
456,Google,NaN,Θεικο!Απιστευτο!ΥπεροχοΜαγικο!Αριστο!,Θεικο!Απιστευτο!ΥπεροχοΜαγικο!Αριστο!

In [16]:
# Does a specific site contain reviews with missing language labels?
pelagos_unknown_language["Review Site"].value_counts(dropna=False)

Review Site
Google         66
TripAdvisor     2
Name: count, dtype: int64

In [17]:
#install language detection 
%pip install langdetect

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels
Requirement already satisfied: langdetect in /home/8dff46cf-09d4-4d6f-9501-4575fba38b61/.local/lib/python3.12/site-packages (1.0.9)
Requirement already satisfied: six in /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages (from langdetect) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from langdetect import detect, DetectorFactory

DetectorFactory.seed = 0

def detect_language(text):
    try:
        if pd.isna(text) or len(str(text).strip()) < 3:
            return "unknown"
        return detect(str(text))
    except:
        return "unknown"

    pelagos_unknown_language= pelagos_nlp[pelagos_nlp["Language"].isna()
        ].copy()

pelagos_unknown_language["Detect_Language"]= (pelagos_unknown_language["Review_Text"].apply(detect_language)
                                             )

pelagos_unknown_language["Detect_Language"].value_counts(dropna=False)

Detect_Language
el    65
hr     1
ca     1
cy     1
Name: count, dtype: int64

In [27]:
pelagos_unknown_language[
    pelagos_unknown_language["Detect_Language"] !="el"
][["Review Site", "Review_Text", "Detect_Language"]]

    Review Site                              Review_Text Detect_Language
185      Google                                  Optimal              hr
653      Google                             Apla super 👏              ca
962      Google  mai abhi gyi nhi hu pr achha h jrur jae              cy

In [32]:
#Creating a final language column while preserving the original labels from Revinate 
pelagos_nlp["Language_Final"] = pelagos_nlp["Language"]

# missing language reviews are confidently detected as Greek
greek_indices =pelagos_unknown_language[
    pelagos_unknown_language["Detect_Language"] == "el"].index
pelagos_nlp.loc[greek_indices, "Language_Final"] = "Greek"

# the 3 ambiguous short reviews to be labeled as Other or Unknown
other_indices= pelagos_unknown_language[
    pelagos_unknown_language["Detect_Language"] != "el"
    ].index
pelagos_nlp.loc[other_indices, "Language_Final"] = "Other/Unknown"

pelagos_nlp["Language_Final"].value_counts(dropna=False)

Language_Final
English                  752
Greek                     65
Japanese                  26
Portuguese                23
Chinese (Traditional)     18
Spanish                   16
French                    16
German                    12
Italian                    7
Chinese (Simplified)       4
Korean                     4
Russian                    4
Arabic                     3
Other/Unknown              3
Polish                     3
Danish                     2
Turkish                    2
Hebrew                     2
Dutch                      1
Name: count, dtype: int64

In [43]:
#Check for missing or short review text 
pelagos_nlp["Review_Length"] = (
pelagos_nlp["Review_Text"]
.fillna("")
.astype(str)
.str.strip()
.str.len()
)

print("Total reviews:", len(pelagos_nlp))
print("Missing Review_Text:", pelagos_nlp["Review_Text"].isna().sum())
print("Empty reviews:", (pelagos_nlp["Review_Length"] == 0).sum())
print("Very short reviews (under 10 characters):",
(pelagos_nlp["Review_Length"] < 10).sum())

Total reviews: 963
Missing Review_Text: 0
Empty reviews: 0
Very short reviews (under 10 characters): 22

In [45]:
#Inspecting the very short reviews before deciding the keep them or not 
pelagos_nlp[
    pelagos_nlp["Review_Length"] <10
    ][["Review_Text", "Language_Final", "Review_Length"]]

    Review_Text         Language_Final  Review_Length
66    Very good                English              9
71    Excellent                English              9
107   Excellent                English              9
115   Very Good                English              9
137     Awesome                English              7
138   Soggiorno             Portuguese              9
142     Awesome                English              7
185     Optimal          Other/Unknown              7
212    Fabulous                English              8
311   環境不錯，設施齊全  Chinese (Traditional)              9
433       Super                English              5
461   Very good                English              9
468   Πολύ καλό                  Greek              9
478   Τέλειο!!!                  Greek              9
480     Awesome                English              7
533   Excellent                English              9
639      Τελειο                  Greek              6
650      φοβερο                  Greek              6
651     Άριστο!                  Greek              7
703   Excellent                English              9
894   Wonderful                English              9
917   Belíssimo                English              9

In [48]:
import re

pelagos_nlp["Clean_Text"] = (
pelagos_nlp["Review_Text"]
.astype(str)
.str.lower()
.str.replace(r"http\S+|www\S+", " ", regex=True)
.str.replace(r"\s+", " ", regex=True)
.str.strip()
)

pelagos_nlp[["Review_Text", "Clean_Text"]].head(10)

,Review_Text,Clean_Text
0,The best way to experience Santorini… This hot...,the best way to experience santorini… this hot...
1,Worth every penny. The staff were amazing. The...,worth every penny. the staff were amazing. the...
2,非常滿意，環境非常好👍,非常滿意，環境非常好👍
3,"Excelente atención desde antes de llegar, adem...","excelente atención desde antes de llegar, adem..."
4,Good: 很美的日落景,good: 很美的日落景
5,Walkability: Many steps and steep,walkability: many steps and steep
6,Good: Beautiful hotel! The staff was incredib...,good: beautiful hotel! the staff was incredibl...
7,"Pretty much flawless The service, amenities, f...","pretty much flawless the service, amenities, f..."
8,Truly lives up to its claim of being one of th...,truly lives up to its claim of being one of th...
9,Outstanding Excelente atención desde antes de ...,outstanding excelente atención desde antes de ...

In [49]:
# Checking the data before continuing

print("Total reviews:", len(pelagos_nlp))

print("Missing reviews:",
pelagos_nlp["Review_Text"].isna().sum())

print("Short reviews:",
(pelagos_nlp["Review_Length"] < 10).sum())

print("Duplicate reviews:",
pelagos_nlp["Review_Text"].duplicated().sum())

print("\nLanguages:")
print(pelagos_nlp["Language_Final"].value_counts())

Total reviews: 963
Missing reviews: 0
Short reviews: 22
Duplicate reviews: 85

Languages:
Language_Final
English                  752
Greek                     65
Japanese                  26
Portuguese                23
Chinese (Traditional)     18
Spanish                   16
French                    16
German                    12
Italian                    7
Chinese (Simplified)       4
Korean                     4
Russian                    4
Arabic                     3
Other/Unknown              3
Polish                     3
Danish                     2
Turkish                    2
Hebrew                     2
Dutch                      1
Name: count, dtype: int64

In [50]:
# Check repeated review texts

duplicates = pelagos_nlp[
pelagos_nlp.duplicated(subset=["Review_Text"], keep=False)
]

duplicates[
["Review_Text", "Language_Final", "Review_Length"]
].sort_values("Review_Text").head(30)

,Review_Text,Language_Final,Review_Length
634,A beautiful stay in a sensational property. Go...,English,178
620,A beautiful stay in a sensational property. Go...,English,178
201,A lovely stay spoiled by a chincy tipping poli...,English,547
217,A lovely stay spoiled by a chincy tipping poli...,English,547
260,A wonderful stay. I throughly enjoyed the atmo...,English,303
268,A wonderful stay. I throughly enjoyed the atmo...,English,303
129,"Absolutely fantastic. Good: Everything, the lo...",English,106
148,"Absolutely fantastic. Good: Everything, the lo...",English,106
273,Absolutely perfect! Good: Our stay was again a...,English,384
709,Absolutely perfect! Good: Our stay was again a...,English,384
259,Amazing hotel with fantastic caldera views Goo...,English,135
267,Amazing hotel with fantastic caldera views Goo...,English,135
122,Amazing stay. Thank you for a relaxing week! G...,English,132
112,Amazing stay. Thank you for a relaxing week! G...,English,132
862,Amazing. Spectacular views Good: Location beau...,English,51
842,Amazing. Spectacular views Good: Location beau...,English,51
82,"Among the best hotels in the world, have no do...",English,209
78,"Among the best hotels in the world, have no do...",English,209
137,Awesome,English,7
480,Awesome,English,7
142,Awesome,English,7
324,Bad: The jet tub wasn’t cleaned regularly and ...,English,149
309,Bad: The jet tub wasn’t cleaned regularly and ...,English,149
893,Beautiful hotel with great Michelin restaurant...,English,194
901,Beautiful hotel with great Michelin restaurant...,English,194
52,Beautiful location. Wonderful attentive staff....,English,513
330,Beautiful location. Wonderful attentive staff....,English,513
596,Beautiful stay in the best area of Santorini G...,English,726
608,Beautiful stay in the best area of Santorini G...,English,726
633,Charming property with amazing views and very ...,English,562

In [51]:
# Remove exact duplicate reviews

pelagos_nlp = pelagos_nlp.drop_duplicates(
subset=["Review_Text"],
keep="first"
).copy()

pelagos_nlp.reset_index(drop=True, inplace=True)

print("Reviews after removing duplicates:", len(pelagos_nlp))

Reviews after removing duplicates: 878

In [52]:
# Mark short reviews

pelagos_nlp["Short_Review"] = pelagos_nlp["Review_Length"] < 10

print("Total reviews:", len(pelagos_nlp))
print("Short reviews:", pelagos_nlp["Short_Review"].sum())

Total reviews: 878
Short reviews: 16

In [53]:
# Create English dataset for NLP

pelagos_english = pelagos_nlp[
pelagos_nlp["Language_Final"] == "English"
].copy()

print("All reviews:", len(pelagos_nlp))
print("English reviews:", len(pelagos_english))
print("Other languages:", len(pelagos_nlp) - len(pelagos_english))

All reviews: 878
English reviews: 667
Other languages: 211

In [55]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

pelagos_english["Processed_Text"] = pelagos_english["Clean_Text"].apply(
lambda text: " ".join(
lemmatizer.lemmatize(word)
for word in text.split()
if word.isalpha() and word not in stop_words
)
)

pelagos_english[["Clean_Text", "Processed_Text"]].head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/8dff46cf-09d4-4d6f-9501-
[nltk_data]     4575fba38b61/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     /home/8dff46cf-09d4-4d6f-9501-
[nltk_data]     4575fba38b61/nltk_data...

,Clean_Text,Processed_Text
0,the best way to experience santorini… this hot...,best way experience hotel absolutely suite vie...
1,worth every penny. the staff were amazing. the...,worth every staff sunset
5,walkability: many steps and steep,many step steep
6,good: beautiful hotel! the staff was incredibl...,beautiful staff incredibly professional litera...
7,"pretty much flawless the service, amenities, f...",pretty much flawless ambiance enjoyed gorgeous...
8,truly lives up to its claim of being one of th...,truly life claim one leading hotel excellent v...
10,"25th wedding anniversary holiday well, having ...",wedding anniversary holiday read positive simp...
14,we had high expectation of this prestigious ho...,high expectation prestigious best part experie...
15,rooms: 5/5 | service: 5/5 | location: 5/5 hote...,hotel highlight great romantic
16,my husband and i visited here early october. t...,husband visited early property stunning staff ...

In [56]:
pelagos_nlp.to_excel("Pelagos_Preprocessed_All_Languages.xlsx", index=False)

pelagos_english.to_excel("Pelagos_Preprocessed_English.xlsx", index=False)

print("Files saved!")

Files saved!